name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/pushistikMC/android_kernel_samsung_a05m
          kernel-branch: main
          config: a05m_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 11
          aosp-clang-version: r383902
          ccache: true
          kvm: false
          anykernel3: true
